// Task view + edit in one page — every field editable, status included
// (review round 1).
import { notFound } from 'next/navigation'
import { requireSessionOrRedirect } from '@/lib/session'
import { getTask } from '@/lib/data/tasks'
import {
  listAccountOptions,
  listPersonOptions,
  listPicklistOptions,
  listProjectOptions,
  listUserOptions,
} from '@/lib/data/options'
import { TaskForm } from '../task-form'
import { updateTaskAction } from '../actions'

export const dynamic = 'force-dynamic'

export default async function TaskPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSessionOrRedirect()
  const { id } = await params
  const taskId = Number(id)
  if (!Number.isInteger(taskId)) notFound()
  const task = await getTask(taskId)
  if (!task) notFound()

  const [accounts, projects, people, users, taskTypes] = await Promise.all([
    listAccountOptions(),
    listProjectOptions(),
    listPersonOptions(),
    listUserOptions(),
    listPicklistOptions('task_type'),
  ])
  const accountNames: Record<number, string> = {}
  for (const a of accounts) accountNames[a.id] = a.name

  return (
    <>
      <h1>
        {task.title} {task.isAutoGenerated && <span className="badge">🔁 auto</span>}
      </h1>
      {task.completedDate && <p className="muted">Completed {task.completedDate}</p>}
      <div className="card">
        <TaskForm
          action={updateTaskAction}
          taskId={task.id}
          initial={{
            title: task.title,
            description: task.description,
            typeId: task.typeId,
            status: task.status,
            dueDate: task.dueDate,
            assigneeUserId: task.assigneeUserId,
            projectId: task.projectId,
            accountId: task.accountId,
            personId: task.personId,
          }}
          options={{ accounts, projects, people, users, taskTypes, accountNames }}
          submitLabel="Save changes"
        />
      </div>
    </>
  )
}
