// Tasks list — mine/all, status filter, search, pagination (review round 1).
import Link from 'next/link'
import { requireSessionOrRedirect } from '@/lib/session'
import { listTasks } from '@/lib/data/tasks'
import { parsePage } from '@/lib/list'
import { Pagination, SearchBar } from '@/components/list-controls'
import { completeTaskAction } from './actions'
import type { TaskStatus } from '@/db/schema'

export const dynamic = 'force-dynamic'

const STATUS_OPTIONS = ['open_all', 'open', 'in_progress', 'done', 'cancelled'] as const

export default async function TasksPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; status?: string; who?: string; page?: string }>
}) {
  const session = await requireSessionOrRedirect()
  const sp = await searchParams
  const q = sp.q?.trim() ?? ''
  const status = (STATUS_OPTIONS as readonly string[]).includes(sp.status ?? '')
    ? (sp.status as TaskStatus | 'open_all')
    : 'open_all'
  const who = sp.who === 'all' ? 'all' : 'mine'
  const result = await listTasks(session, {
    q: q || undefined,
    status,
    assignee: who,
    page: parsePage(sp.page),
  })

  const params = {
    ...(q ? { q } : {}),
    ...(status !== 'open_all' ? { status } : {}),
    ...(who !== 'mine' ? { who } : {}),
  }

  return (
    <>
      <div className="toolbar">
        <h1>{who === 'mine' ? 'My Tasks' : 'All Tasks'}</h1>
        <Link className="button" href="/tasks/new">
          + New task
        </Link>
      </div>

      <SearchBar action="/tasks" q={q} placeholder="Search title, project, account…">
        <select name="who" defaultValue={who}>
          <option value="mine">Assigned to me</option>
          <option value="all">Everyone</option>
        </select>
        <select name="status" defaultValue={status}>
          <option value="open_all">Open + in progress</option>
          <option value="open">Open</option>
          <option value="in_progress">In progress</option>
          <option value="done">Done</option>
          <option value="cancelled">Cancelled</option>
        </select>
      </SearchBar>

      <table className="list">
        <thead>
          <tr>
            <th>Task</th>
            <th>Related to</th>
            <th>Assignee</th>
            <th>Due</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {result.rows.length === 0 && (
            <tr>
              <td colSpan={6} className="muted">
                Nothing here — add a task.
              </td>
            </tr>
          )}
          {result.rows.map((t) => (
            <tr key={t.id}>
              <td>
                <Link href={`/tasks/${t.id}`}>{t.title}</Link>{' '}
                {t.isAutoGenerated && <span className="badge">🔁 auto</span>}
                {t.typeLabel && <span className="muted"> · {t.typeLabel}</span>}
              </td>
              <td>
                {t.projectId ? (
                  <Link href={`/projects/${t.projectId}`}>{t.projectName}</Link>
                ) : t.accountId ? (
                  <Link href={`/accounts/${t.accountId}`}>{t.accountName}</Link>
                ) : t.personName ? (
                  t.personName
                ) : (
                  <span className="muted">—</span>
                )}
              </td>
              <td>{t.assigneeName}</td>
              <td>{t.dueDate ?? ''}</td>
              <td>
                <span className="badge">{t.status.replace('_', ' ')}</span>
              </td>
              <td>
                {(t.status === 'open' || t.status === 'in_progress') &&
                  t.assigneeUserId === session.userId && (
                    <form action={completeTaskAction}>
                      <input type="hidden" name="taskId" value={t.id} />
                      <button className="quiet">Done</button>
                    </form>
                  )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <Pagination paged={result} basePath="/tasks" params={params} />
    </>
  )
}
