// Data access for tasks (02 §8.1) and the reorder follow-up loop (ADR-0029,
// K3 — spec-correct: per-project interval, complete-one-schedules-next,
// order date resets the clock, pause is first-class).
import 'server-only'
import { and, asc, eq, sql } from 'drizzle-orm'
import { db } from '@/lib/db'
import { accounts, projects, purchaseOrders, tasks, type TaskStatus } from '@/db/schema'
import type { AppSession } from '@/lib/session'

export interface TaskDto {
  id: number
  title: string
  status: TaskStatus
  projectId: number | null
  projectName: string | null
  accountName: string | null
  dueDate: string | null
  isAutoGenerated: boolean
}

export async function listMyOpenTasks(session: AppSession): Promise<TaskDto[]> {
  return db
    .select({
      id: tasks.id,
      title: tasks.title,
      status: tasks.status,
      projectId: tasks.projectId,
      projectName: projects.name,
      accountName: accounts.name,
      dueDate: tasks.dueDate,
      isAutoGenerated: tasks.isAutoGenerated,
    })
    .from(tasks)
    .leftJoin(projects, eq(tasks.projectId, projects.id))
    .leftJoin(accounts, eq(tasks.accountId, accounts.id))
    .where(
      and(
        eq(tasks.assigneeUserId, session.userId),
        sql`${tasks.status} IN ('open', 'in_progress')`,
      ),
    )
    .orderBy(sql`${tasks.dueDate} asc nulls last`, asc(tasks.id))
}

export async function createTask(
  session: AppSession,
  input: {
    title: string
    description?: string | null
    projectId?: number | null
    accountId?: number | null
    personId?: number | null
    dueDate?: string | null
    assigneeUserId?: string // N4: users may assign to each other
  },
): Promise<number> {
  const rows = await db
    .insert(tasks)
    .values({
      title: input.title,
      description: input.description ?? null,
      projectId: input.projectId ?? null,
      accountId: input.accountId ?? null,
      personId: input.personId ?? null,
      dueDate: input.dueDate ?? null,
      assigneeUserId: input.assigneeUserId ?? session.userId,
      createdById: session.userId,
      updatedById: session.userId,
    })
    .returning({ id: tasks.id })
  return rows[0].id
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10)
}

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`)
  d.setUTCDate(d.getUTCDate() + days)
  return d.toISOString().slice(0, 10)
}

/**
 * Complete a task (scoped to the assignee). If it is an auto-generated
 * reorder follow-up on a project with an active interval, the NEXT one is
 * scheduled one interval ahead in the same transaction — the client-spec
 * loop: completing one schedules the next (ADR-0029 §2.4).
 */
export async function completeTask(session: AppSession, taskId: number): Promise<boolean> {
  return db.transaction(async (tx) => {
    const rows = await tx
      .update(tasks)
      .set({
        status: 'done',
        completedDate: todayIso(),
        updatedById: session.userId,
        updatedAt: new Date(),
      })
      .where(
        and(
          eq(tasks.id, taskId),
          eq(tasks.assigneeUserId, session.userId),
          sql`${tasks.status} IN ('open', 'in_progress')`,
        ),
      )
      .returning({
        id: tasks.id,
        projectId: tasks.projectId,
        isAutoGenerated: tasks.isAutoGenerated,
        typeId: tasks.typeId,
      })
    const done = rows[0]
    if (!done) return false

    if (done.isAutoGenerated && done.projectId != null) {
      const proj = await tx
        .select({
          id: projects.id,
          name: projects.name,
          ownerUserId: projects.ownerUserId,
          intervalDays: projects.followupIntervalDays,
          paused: projects.followupPaused,
          status: projects.status,
        })
        .from(projects)
        .where(eq(projects.id, done.projectId))
        .limit(1)
      const p = proj[0]
      if (p && !p.paused && p.status === 'won' && p.intervalDays != null) {
        await tx.insert(tasks).values({
          title: `Reorder follow-up: ${p.name}`,
          typeId: done.typeId,
          projectId: p.id,
          assigneeUserId: p.ownerUserId,
          dueDate: addDays(todayIso(), p.intervalDays),
          isAutoGenerated: true,
          recurrenceParentTaskId: done.id,
          createdById: session.userId,
          updatedById: session.userId,
        })
      }
    }
    return true
  })
}

/**
 * Scheduler tick (cron route). Covers the case the completion chain cannot:
 * a project that has an interval but no open auto-task (first Won, an order
 * arrived and reset the clock, or recurrence was just unpaused).
 *
 * Due date = most recent non-void order date + interval; falls back to the
 * Won date when no order exists yet (02 §11, D12: the clock counts from the
 * most recent order). Idempotent: "one open auto-task at a time" per
 * project (testing priority 7).
 */
export async function generateFollowupTasks(): Promise<number> {
  const candidates = await db
    .select({
      id: projects.id,
      name: projects.name,
      ownerUserId: projects.ownerUserId,
      intervalDays: projects.followupIntervalDays,
    })
    .from(projects)
    .where(
      and(
        eq(projects.type, 'consumable'),
        eq(projects.status, 'won'),
        eq(projects.followupPaused, false),
        sql`${projects.followupIntervalDays} IS NOT NULL`,
      ),
    )

  let created = 0
  for (const p of candidates) {
    const open = await db
      .select({ id: tasks.id })
      .from(tasks)
      .where(
        and(
          eq(tasks.projectId, p.id),
          eq(tasks.isAutoGenerated, true),
          sql`${tasks.status} IN ('open', 'in_progress')`,
        ),
      )
      .limit(1)
    if (open.length > 0) continue // the idempotency rule

    const anchor = await db
      .select({
        lastPoDate: sql<string | null>`max(${purchaseOrders.poDate})`,
      })
      .from(purchaseOrders)
      .where(and(eq(purchaseOrders.projectId, p.id), eq(purchaseOrders.isVoid, false)))
    const wonAt = await db
      .select({ changedAt: sql<string>`max(changed_at)::date` })
      .from(sql`project_history`)
      .where(sql`project_id = ${p.id} AND field = 'status' AND to_value = 'won'`)

    const base = anchor[0]?.lastPoDate ?? wonAt[0]?.changedAt ?? todayIso()
    const due = addDays(base, p.intervalDays!)
    if (due > todayIso()) continue // not due yet

    await db.insert(tasks).values({
      title: `Reorder follow-up: ${p.name}`,
      projectId: p.id,
      assigneeUserId: p.ownerUserId,
      dueDate: due,
      isAutoGenerated: true,
      createdById: p.ownerUserId,
      updatedById: p.ownerUserId,
    })
    created++
  }
  return created
}
