// Data access for tasks (02 §8.1) and the reorder follow-up loop (ADR-0029,
// K3). Full CRUD: a task may relate to a project, an account, and a person
// (any or none), carry a type, description and assignee, and be updated
// after creation (review round 1).
import 'server-only'
import { and, asc, count, eq, ilike, or, sql, type SQL } from 'drizzle-orm'
import { alias } from 'drizzle-orm/pg-core'
import { db } from '@/lib/db'
import {
  accounts,
  people,
  picklists,
  projects,
  purchaseOrders,
  tasks,
  users,
  type TaskStatus,
} from '@/db/schema'
import { likePattern, offsetFor, PAGE_SIZE, paged, type Paged } from '@/lib/list'
import type { AppSession } from '@/lib/session'

export interface TaskDto {
  id: number
  title: string
  status: TaskStatus
  typeLabel: string | null
  projectId: number | null
  projectName: string | null
  accountId: number | null
  accountName: string | null
  personName: string | null
  assigneeUserId: string
  assigneeName: string | null
  dueDate: string | null
  isAutoGenerated: boolean
}

export interface TaskDetailDto extends TaskDto {
  description: string | null
  typeId: number | null
  personId: number | null
  completedDate: string | null
}

const assignee = alias(users, 'assignee')

const listSelection = {
  id: tasks.id,
  title: tasks.title,
  status: tasks.status,
  typeLabel: picklists.label,
  projectId: tasks.projectId,
  projectName: projects.name,
  accountId: tasks.accountId,
  accountName: accounts.name,
  personName: people.name,
  assigneeUserId: tasks.assigneeUserId,
  assigneeName: assignee.name,
  dueDate: tasks.dueDate,
  isAutoGenerated: tasks.isAutoGenerated,
}

function baseQuery() {
  return db
    .select(listSelection)
    .from(tasks)
    .leftJoin(projects, eq(tasks.projectId, projects.id))
    .leftJoin(accounts, eq(tasks.accountId, accounts.id))
    .leftJoin(people, eq(tasks.personId, people.id))
    .leftJoin(picklists, eq(tasks.typeId, picklists.id))
    .leftJoin(assignee, eq(tasks.assigneeUserId, assignee.id))
}

export interface TaskFilters {
  q?: string
  status?: TaskStatus | 'open_all' // open_all = open + in_progress
  assignee?: 'mine' | 'all'
  page?: number
}

export async function listTasks(session: AppSession, f: TaskFilters): Promise<Paged<TaskDto>> {
  const page = f.page ?? 1
  const conditions: SQL[] = []
  if (f.assignee !== 'all') conditions.push(eq(tasks.assigneeUserId, session.userId))
  if (f.status === 'open_all' || !f.status) {
    conditions.push(sql`${tasks.status} IN ('open', 'in_progress')`)
  } else {
    conditions.push(eq(tasks.status, f.status))
  }
  if (f.q) {
    const p = likePattern(f.q)
    conditions.push(
      or(ilike(tasks.title, p), ilike(projects.name, p), ilike(accounts.name, p))!,
    )
  }
  const where = and(...conditions)

  const rows = await baseQuery()
    .where(where)
    .orderBy(sql`${tasks.dueDate} asc nulls last`, asc(tasks.id))
    .limit(PAGE_SIZE)
    .offset(offsetFor(page))
  const totalRows = await db
    .select({ n: count() })
    .from(tasks)
    .leftJoin(projects, eq(tasks.projectId, projects.id))
    .leftJoin(accounts, eq(tasks.accountId, accounts.id))
    .where(where)
  return paged(rows, totalRows[0].n, page)
}

export async function getTask(id: number): Promise<TaskDetailDto | null> {
  const rows = await baseQuery().where(eq(tasks.id, id)).limit(1)
  const base = rows[0]
  if (!base) return null
  const detail = await db
    .select({
      description: tasks.description,
      typeId: tasks.typeId,
      personId: tasks.personId,
      completedDate: tasks.completedDate,
    })
    .from(tasks)
    .where(eq(tasks.id, id))
    .limit(1)
  return { ...base, ...detail[0] }
}

export interface TaskInput {
  title: string
  description?: string | null
  typeId?: number | null
  dueDate?: string | null
  assigneeUserId?: string // N4: users may assign to each other
  projectId?: number | null
  accountId?: number | null
  personId?: number | null
}

export async function createTask(session: AppSession, input: TaskInput): Promise<number> {
  const rows = await db
    .insert(tasks)
    .values({
      title: input.title,
      description: input.description ?? null,
      typeId: input.typeId ?? null,
      dueDate: input.dueDate ?? null,
      assigneeUserId: input.assigneeUserId ?? session.userId,
      projectId: input.projectId ?? null,
      accountId: input.accountId ?? null,
      personId: input.personId ?? null,
      createdById: session.userId,
      updatedById: session.userId,
    })
    .returning({ id: tasks.id })
  return rows[0].id
}

/** Flat permissions (ADR-0006): any user may update any task. */
export async function updateTask(
  session: AppSession,
  taskId: number,
  input: TaskInput & { status: TaskStatus },
): Promise<boolean> {
  const rows = await db
    .update(tasks)
    .set({
      title: input.title,
      description: input.description ?? null,
      typeId: input.typeId ?? null,
      dueDate: input.dueDate ?? null,
      assigneeUserId: input.assigneeUserId ?? session.userId,
      projectId: input.projectId ?? null,
      accountId: input.accountId ?? null,
      personId: input.personId ?? null,
      status: input.status,
      completedDate:
        input.status === 'done' ? sql`coalesce(${tasks.completedDate}, current_date)` : null,
      updatedById: session.userId,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, taskId))
    .returning({ id: tasks.id })
  return rows.length > 0
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10)
}

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`)
  d.setUTCDate(d.getUTCDate() + days)
  return d.toISOString().slice(0, 10)
}

/**
 * Complete a task (scoped to the assignee). If it is an auto-generated
 * reorder follow-up on a project with an active interval, the NEXT one is
 * scheduled one interval ahead in the same transaction (ADR-0029 §2.4).
 */
export async function completeTask(session: AppSession, taskId: number): Promise<boolean> {
  return db.transaction(async (tx) => {
    const rows = await tx
      .update(tasks)
      .set({
        status: 'done',
        completedDate: todayIso(),
        updatedById: session.userId,
        updatedAt: new Date(),
      })
      .where(
        and(
          eq(tasks.id, taskId),
          eq(tasks.assigneeUserId, session.userId),
          sql`${tasks.status} IN ('open', 'in_progress')`,
        ),
      )
      .returning({
        id: tasks.id,
        projectId: tasks.projectId,
        isAutoGenerated: tasks.isAutoGenerated,
        typeId: tasks.typeId,
      })
    const done = rows[0]
    if (!done) return false

    if (done.isAutoGenerated && done.projectId != null) {
      const proj = await tx
        .select({
          id: projects.id,
          name: projects.name,
          ownerUserId: projects.ownerUserId,
          intervalDays: projects.followupIntervalDays,
          paused: projects.followupPaused,
          status: projects.status,
        })
        .from(projects)
        .where(eq(projects.id, done.projectId))
        .limit(1)
      const p = proj[0]
      if (p && !p.paused && p.status === 'won' && p.intervalDays != null) {
        await tx.insert(tasks).values({
          title: `Reorder follow-up: ${p.name}`,
          typeId: done.typeId,
          projectId: p.id,
          assigneeUserId: p.ownerUserId,
          dueDate: addDays(todayIso(), p.intervalDays),
          isAutoGenerated: true,
          recurrenceParentTaskId: done.id,
          createdById: session.userId,
          updatedById: session.userId,
        })
      }
    }
    return true
  })
}

/**
 * Scheduler tick (cron route) — covers what the completion chain cannot:
 * a project with an interval but no open auto-task. Due date = most recent
 * non-void order date + interval, falling back to the Won date. Idempotent:
 * one open auto-task at a time per project (testing priority 7).
 */
export async function generateFollowupTasks(): Promise<number> {
  const candidates = await db
    .select({
      id: projects.id,
      name: projects.name,
      ownerUserId: projects.ownerUserId,
      intervalDays: projects.followupIntervalDays,
    })
    .from(projects)
    .where(
      and(
        eq(projects.type, 'consumable'),
        eq(projects.status, 'won'),
        eq(projects.followupPaused, false),
        sql`${projects.followupIntervalDays} IS NOT NULL`,
      ),
    )

  let created = 0
  for (const p of candidates) {
    const open = await db
      .select({ id: tasks.id })
      .from(tasks)
      .where(
        and(
          eq(tasks.projectId, p.id),
          eq(tasks.isAutoGenerated, true),
          sql`${tasks.status} IN ('open', 'in_progress')`,
        ),
      )
      .limit(1)
    if (open.length > 0) continue // the idempotency rule

    const anchor = await db
      .select({ lastPoDate: sql<string | null>`max(${purchaseOrders.poDate})` })
      .from(purchaseOrders)
      .where(and(eq(purchaseOrders.projectId, p.id), eq(purchaseOrders.isVoid, false)))
    const wonAt = await db
      .select({ changedAt: sql<string>`max(changed_at)::date` })
      .from(sql`project_history`)
      .where(sql`project_id = ${p.id} AND field = 'status' AND to_value = 'won'`)

    const base = anchor[0]?.lastPoDate ?? wonAt[0]?.changedAt ?? todayIso()
    const due = addDays(base, p.intervalDays!)
    if (due > todayIso()) continue // not due yet

    await db.insert(tasks).values({
      title: `Reorder follow-up: ${p.name}`,
      projectId: p.id,
      assigneeUserId: p.ownerUserId,
      dueDate: due,
      isAutoGenerated: true,
      createdById: p.ownerUserId,
      updatedById: p.ownerUserId,
    })
    created++
  }
  return created
}

// Kept for the My Tasks landing summary (unpaged, mine, open).
export async function listMyOpenTasks(session: AppSession): Promise<TaskDto[]> {
  const rows = await baseQuery()
    .where(
      and(eq(tasks.assigneeUserId, session.userId), sql`${tasks.status} IN ('open', 'in_progress')`),
    )
    .orderBy(sql`${tasks.dueDate} asc nulls last`, asc(tasks.id))
    .limit(100)
  return rows
}
